# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'e:\Cosas de guardar\Uni\Año 5\Segundo cuatrimestre\Inteligencia artificial 2\TP Integrador\Codigo\Codigo Fuente\Interfaz_Principal.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(600, 320)
        MainWindow.setMinimumSize(QtCore.QSize(600, 320))
        MainWindow.setMaximumSize(QtCore.QSize(600, 300))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 20, 601, 71))
        font = QtGui.QFont()
        font.setFamily("PMingLiU-ExtB")
        font.setPointSize(48)
        self.label.setFont(font)
        self.label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 110, 571, 161))
        self.label_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_2.setObjectName("label_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 600, 21))
        self.menubar.setObjectName("menubar")
        self.menuAlgoritmo_k_nn = QtWidgets.QMenu(self.menubar)
        self.menuAlgoritmo_k_nn.setObjectName("menuAlgoritmo_k_nn")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.Analizar_Dataset = QtWidgets.QAction(MainWindow)
        self.Analizar_Dataset.setObjectName("Analizar_Dataset")
        self.Volver = QtWidgets.QAction(MainWindow)
        self.Volver.setObjectName("Volver")
        self.menuAlgoritmo_k_nn.addAction(self.Analizar_Dataset)
        self.menubar.addAction(self.menuAlgoritmo_k_nn.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "BIENVENIDO"))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p>GUÍA DEL USUARIO</p><p>En la esquina superior izquierda se encuentra el menú con las distintas funcionalidades que posee esta aplicación.</p><p>1-Pestaña de &quot;Algoritmo k-nn&quot;:</p><p>1.1-Pestaña &quot;Analizar Dataset&quot;:Al presionar esta pestaña se trasladará a la interfaz donde siguiendo los pasos podrá <br/>implementar el Algoritmo k-nn.</p></body></html>"))
        self.menuAlgoritmo_k_nn.setTitle(_translate("MainWindow", "Algoritmo k-nn"))
        self.Analizar_Dataset.setText(_translate("MainWindow", "Analizar Dataset"))
        self.Volver.setText(_translate("MainWindow", "Volver al inicio"))
